import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/MySlices.module.scss'
import Header from '@/components/Header'
import MySlicesTable from '@/components/MySlicesTable'

const inter = Inter({ subsets: ['latin'] })

export default function MySlices() {

  const mySlices = [
    { id: 1, imagePath: '/sneaker-circle.png', title: 'Nike das Esquom Unique Edition', date: '05/03/24', auctionStatus: 'Closed', amount: 2, paidValue: 0.2, updatedValue: 1.5},
    { id: 2, imagePath: '/sneaker-circle2.png', title: 'Adidas Fly Ultimate Exclusive', date: '05/03/24', auctionStatus: 'Pending', amount: 2, paidValue: 0.2, updatedValue: 0.5},
    { id: 3, imagePath: '/sneaker-circle3.png', title: 'Jordan Last City Series', date: '05/03/24', auctionStatus: 'Live', amount: 2, paidValue: 0.2, updatedValue: 0.3},
    { id: 4, imagePath: '/sneaker-circle4.png', title: 'Puma Green Beast Glow', date: '05/03/24', auctionStatus: 'Live', amount: 2, paidValue: 0.2, updatedValue: 0.5}
  ];

  return (
    <>
      <Head>
        <title>My Slices</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
    
        <div className={styles.mainWrapper}>
          <h1>My Slices</h1>
          <MySlicesTable slices={mySlices} />
        </div>
      </main>
    </>
  )
}